### ISSUE TITLE
Suggestions/Tags as objects/React components instead of simple strings?

### ISSUE THREAD

**Issue by wes1278** [morzzz007/react-tagging#1]
Hello @morzzz007,

Great job building this library - especially having the ability to define a promise or an array as the suggestions source! This feature is exactly what I need.

I'm having a bit of a hard time finding what needs to be done to support allowing the concept of a "label" and a "value" for a tag. My use case is that I need access to the Id of the thing I'm pulling as a suggestion asynchronously; however, I want to display the "name" instead of the id.

Could you help point me in the right direction on what would need to change? I'm more familiar with JSX and I'm getting lost in the details.

Thanks for any help!

-Wes

**Comment by morzzz007** [comment]
Hi @wes1278,

I've updated the code, now it accepts objects like { id: 1, value: 'display value' }, but to be honest I was just playing with react for the first time but never really got the time to deep dive into it (yet). You should check out https://github.com/olahol/react-tagsinput to get some ideas

**Comment by wes1278** [comment]
Wow! Thanks so much. I have seen that other repo you mentioned. I actually much prefer yours. :) It has suggestions based on asynchronous result set already built!

Thanks so much for the quick turnaround. This is great!
